/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconMingcuteAlertLine: typeof import('~icons/mingcute/alert-line.jsx')['default']
  const IconMingcuteArrowDown2Line: typeof import('~icons/mingcute/arrow-down2-line.jsx')['default']
  const IconMingcuteArrowDownFill: typeof import('~icons/mingcute/arrow-down-fill.jsx')['default']
  const IconMingcuteArrowDownLine: typeof import('~icons/mingcute/arrow-down-line.jsx')['default']
  const IconMingcuteArrowDownLine2: typeof import('~icons/mingcute/arrow-down-line2.jsx')['default']
  const IconMingcuteArrowDownLine3: typeof import('~icons/mingcute/arrow-down-line3.jsx')['default']
  const IconMingcuteArrowLeftUpFill: typeof import('~icons/mingcute/arrow-left-up-fill.jsx')['default']
  const IconMingcuteArrowRightDownFill: typeof import('~icons/mingcute/arrow-right-down-fill.jsx')['default']
  const IconMingcuteArrowUp2Line: typeof import('~icons/mingcute/arrow-up2-line.jsx')['default']
  const IconMingcuteArrowUpFill: typeof import('~icons/mingcute/arrow-up-fill.jsx')['default']
  const IconMingcuteArrowUpLine: typeof import('~icons/mingcute/arrow-up-line.jsx')['default']
  const IconMingcuteArrowUpLine2: typeof import('~icons/mingcute/arrow-up-line2.jsx')['default']
  const IconMingcuteCalendar2Fill: typeof import('~icons/mingcute/calendar2-fill.jsx')['default']
  const IconMingcuteCheckFill: typeof import('~icons/mingcute/check-fill.jsx')['default']
  const IconMingcuteCloseFill: typeof import('~icons/mingcute/close-fill.jsx')['default']
  const IconMingcuteDownFill: typeof import('~icons/mingcute/down-fill.jsx')['default']
  const IconMingcuteExitFill: typeof import('~icons/mingcute/exit-fill.jsx')['default']
  const IconMingcuteFullscreenExitFill: typeof import('~icons/mingcute/fullscreen-exit-fill.jsx')['default']
  const IconMingcuteFullscreenFill: typeof import('~icons/mingcute/fullscreen-fill.jsx')['default']
  const IconMingcuteInformationFill: typeof import('~icons/mingcute/information-fill.jsx')['default']
  const IconMingcuteInformationLine: typeof import('~icons/mingcute/information-line.jsx')['default']
  const IconMingcuteLoading3Fill: typeof import('~icons/mingcute/loading3-fill.jsx')['default']
  const IconMingcuteMinimizeFill: typeof import('~icons/mingcute/minimize-fill.jsx')['default']
  const IconMingcuteUpFill: typeof import('~icons/mingcute/up-fill.jsx')['default']
  const IconMingcuteWarningFill: typeof import('~icons/mingcute/warning-fill.jsx')['default']
  const IconTwemojiFlagGermany: typeof import('~icons/twemoji/flag-germany.jsx')['default']
  const IconTwemojiFlagUnitedKingdom: typeof import('~icons/twemoji/flag-united-kingdom.jsx')['default']
}
