/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconMingcuteAlertLine: typeof import('~icons/mingcute/alert-line.jsx')['default']
  const IconMingcuteCloseFill: typeof import('~icons/mingcute/close-fill.jsx')['default']
  const IconMingcuteFullscreenExitFill: typeof import('~icons/mingcute/fullscreen-exit-fill.jsx')['default']
  const IconMingcuteFullscreenFill: typeof import('~icons/mingcute/fullscreen-fill.jsx')['default']
  const IconMingcuteInformationLine: typeof import('~icons/mingcute/information-line.jsx')['default']
  const IconMingcuteLoading3Fill: typeof import('~icons/mingcute/loading3-fill.jsx')['default']
  const IconMingcuteMinimizeFill: typeof import('~icons/mingcute/minimize-fill.jsx')['default']
}
